# CITATION: Faccio, E., Castiglioni, M., & Bell, R. C. (2012). Extracting information from
#   repertory grid data: New perspectives on clinical and assessment practice.
#   Journal of Constructivist Psychology, 25(1), 63-86.
#   DOI: 10.1080/10720537.2012.629508
#
# CONTEXT: This grid was elicited from "Elisabetta," a 17-year-old with an eating disorder,
#   to illustrate methods for extracting clinical information from repertory grids; 13 elements
#   (self, family members, peers, and self-image figures) were rated on 18 bipolar constructs
#   using a -3 to +3 scale (positive = left/emergent pole, negative = right/contrast pole).

args <- list(
  name = c("Elisabetta",
           "Brother",
           "Sister",
           "Parents",
           "Veronica (disliked)",
           "Carlotta (admired)",
           "Federica",
           "Simone",
           "Vanessa",
           "Francesca",
           "As I would like to be",
           "As others see me",
           "As others would like me to be"),
  l.name = c("spontaneous",
             "fragile",
             "happy",
             "reliable",
             "closed",
             "obstinate",
             "strong",
             "obstinate",
             "insensitive",
             "undecided",
             "altruist",
             "simple",
             "impulsive",
             "accommodating",
             "anxious",
             "proud",
             "perfectionist",
             "irritable"),
  r.name = c("false",
             "indifferent",
             "problematic",
             "thinks about own interests",
             "extroverted",
             "weak",
             "weak",
             "hidden",
             "kind-hearted",
             "decided",
             "selfish",
             "less hasty",
             "prudent",
             "ambitious",
             "controls situations",
             "passes over things",
             "hasty",
             "calm"),
  scores = c( 3, -3, -1, -2, -2, -2, -3, -3, -1,  0, -3, -3, -3,
             -2,  1, -1, -1,  0,  2, -2, -1,  1,  0, -1,  0, NA,
             -2, -3, -2,  0,  3, -2, -3, -3, -2, -2, -3, -2, -3,
             -3, -3, -3,  0,  2, -3, -3, -3,  1, -3, -3, -3, -3,
              2,  3,  2,  2,  1, -2,  3,  1,  3, -1,  3,  3,  3,
             -3, -3, -3,  0,  3,  1, -2, -1,  3, -3, -3,  0, NA,
             -2, -2, -3,  1, -2, -2, -3,  0, -1,  1, -3, -1, -3,
             -2, -2, -3,  0,  1, -2,  3,  0, -1,  2, -2,  2, -1,
              2,  3,  2, -1,  0,  3,  3,  3,  1,  1,  3,  2,  3,
              2,  3,  3, -2,  1, -2,  0,  2, -2,  2,  3,  2,  3,
             -2, -2, -2,  0,  2, -3, -2, -3,  1, -1, -3, -2, -3,
             -1, -3, -3,  0, -3,  3,  3,  3, -1, -2, -2, -1, -2,
             -3, -3, -1,  1, -2,  2,  2,  2, -3,  2, -3, -3, -1,
              3,  3,  3, -2,  1, -3, -3, -2,  2,  3,  2,  3,  3,
             -2,  2,  2, -3, -2,  0,  2,  2, -1, -1,  2,  1,  2,
             -2, -2, -2,  2, -2,  2,  2,  2, -2, -1, -2,  2, -2,
             -2, -2, -3,  1, -1, -1, -3, -1,  1,  1, -2, -2, -1,
             -3,  1, -3, -2, -1,  3, -1,  3,  0,  1,  0, -3,  1)
)
grid <- makeRepgrid(args)
grid <- setScale(grid, -3, 3)
